### ISSUE TITLE
Bug: Error when check @postlight/parser package size

### ISSUE THREAD

**Issue by mefengl** [privatenumber/pkg-size.dev#14]
https://pkg-size.dev/@postlight/parser

![image](https://github.com/privatenumber/pkg-size.dev/assets/71683364/eecdb32d-eaf9-444e-8c4e-a2ba010eeaab)

**Comment by privatenumber** [comment]
It looks like the issue is occurring because the `package.json` file is referencing GitHub dependencies, which requires the use of `git` for resolution. Here's the link to the specific line in the `package.json` file: [GitHub Package.json Line](https://github.com/postlight/parser/blob/e8ba7ece291efa4d915d50dd4deeec17d54359f2/package.json#L119).

Unfortunately, it looks like WebContainers doesn't currently support the `git` binary, which is likely causing the problem.

I also want to mention that it's not recommended to reference GitHub branches or tags as dependencies because they can be changed or deleted, leading to installation issues for users. Additionally, this approach could expose users to potential security risks if malicious code is swapped in without requiring a version upgrade.

**Comment by mefengl** [comment]
Got it, thanks for the explanation
