### ISSUE TITLE
Inconsistent bundle size results with Bundlephobia

### ISSUE THREAD

**Issue by Theofilos-Chamalis** [privatenumber/pkg-size.dev#3]
Trying a commonly used dependency as an example, I have stumbled upon a disparity on bundle sizes between Bundlephobia (https://bundlephobia.com/) and Pkg-size (https://pkg-size.dev/). The library in question is `axios` and the results are the following:

- Pkg-size --> https://pkg-size.dev/axios --> 50kb minified
- Bundlephobia --> https://bundlephobia.com/package/axios@1.4.0 --> 29.5kb minified

Which of those 2 solutions is the correct one? What is the reason behind this disparity?

Thanks!

**Comment by privatenumber** [comment]
It's hard to say since I can't confirm Bundlephobia's output, but it looks like they use Webpack to bundle, and Terser (or esbuild) to minify:
https://github.com/pastelsky/package-build-stats/blob/ed3de6ceed4e412d7fbed1540718d0fd71797e9a/src/utils/build.utils.ts#L103

Pkg-size uses esbuild to build and minify.

There isn't a significant minification discrepancy between Terser and esbuild:
https://github.com/privatenumber/minification-benchmarks

But there might be in the bundling process?

So users can verify the build output themselves, I just added a Download button:
<img width="500" src="https://github.com/privatenumber/pkg-size.dev/assets/1075694/b5f2b5d2-21ea-4511-9973-232448b88416">

**Comment by Theofilos-Chamalis** [comment]
Closing this, since an appropriate explanation was given.
